---
- name: Primer play - Ping
  hosts: all
  become: true
  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:
  tags: 
    - prod
    - dev

- name: Cear archivo
  hosts: pr-webservers, pr-filesystem
  become: true
  tasks:
    - name: Crear PEPE
      ansible.builtin.command:
        touch /home/ansible/PROD-pepe.txt
  tags: 
    - prod
  