---
- name: Primer play - Ping
  hosts: all
  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:

- name: Cear archivo
  hosts: all
  tasks:
    - name: Crear PEPE
      ansible.builtin.command:
        touch /home/ansible/pepe.txt

