---
- name: Primer play - Ping
  hosts: production, development
  tags: 
    - prod
    - dev
  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:

- name: Cear archivo
  hosts: production
  tags: 
    - prod
  tasks:
    - name: Crear PEPE
      ansible.builtin.command:
        touch /home/ansible/PROD-pepe.txt
